
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

android.newDsl=true
android.usesSdkInManifest.disallowed=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=true
android.enableAppCompileTimeRClass=true

android.enableJetifier=false

android.dependency.excludeLibraryComponentsFromConstraints=true

android.useAndroidX=true
kotlin.code.style=official